// Real product data extracted from the original ProMuebles catalog (prices) + real catalog specs (Pablo, ago 2026)

const CATEGORIES = [
  { id: '1-plaza', nombre: '1 Plaza' },
  { id: '1-plaza-y-media', nombre: '1 Plaza y Media' },
  { id: '2-plazas', nombre: '2 Plazas' },
  { id: 'queen', nombre: 'Queen' },
  { id: 'king', nombre: 'King' },
  { id: 'personalizacion', nombre: 'Personalización' }
];

const PRODUCTS = [
  // 1 Plaza
  { n: 'Modelo 1 plaza Vip', cat: '1-plaza', medida: '80 × 190 cm', img: 'assets/productos/1-plaza-VIP-1.jpg', price: 380000,
    resumen: '6 cajones, 1 zapatero y 1 baulera.',
    specs: ['6 cajones laterales', '1 baulera central de 145 × 35 × 40 cm', '1 zapatero al pie de 75 cm de ancho', 'Medida total: 193 × 83 cm · Altura: 42 cm', 'Cajones de 40 × 40 × 15 cm', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 600 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] },

  // 1 Plaza y Media
  { n: 'Modelo de Plaza y Media (Esquinero)', cat: '1-plaza-y-media', medida: '100 × 190 cm', img: 'assets/productos/1-plaza-y-media-VIP-Esquinero.jpg', price: 440000,
    clientPhotos: ['assets/producto-fotos/plaza-media-esquinero-1.jpg','assets/producto-fotos/plaza-media-esquinero-2.jpg','assets/producto-fotos/plaza-media-esquinero-3.jpg','assets/producto-fotos/plaza-media-esquinero-4.jpg'],
    resumen: 'Modelo pensado para un rincón: los 6 cajones están todos de un mismo lateral, y el lateral opuesto lo ocupa la baulera, por eso ese lado va contra la pared sin perder acceso a nada. Suma 2 zapateros al pie.',
    specs: ['6 cajones laterales (todos en un mismo lateral)', '1 baulera central de 145 × 58 × 40 cm', '2 zapateros al pie de 45 cm de ancho cada uno (4 pares cada uno)', 'Medida total: 193 × 103 cm · Altura: 42 cm', 'Cajones de 48 × 40 × 15 cm', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 800 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] },
  { n: 'Modelo 8 Vip Plaza y Media', cat: '1-plaza-y-media', medida: '100 × 190 cm', img: 'assets/productos/1-plaza-y-media-VIP-1.jpg', price: 460000,
    resumen: '8 cajones, 2 zapateros y 2 bauleras.',
    specs: ['8 cajones: 4 de cada lado', '2 bauleras en la cabecera de 51 × 38 × 40 cm', '2 zapateros al pie de 45 cm de ancho cada uno (4 pares cada uno)', 'Medida total: 193 × 103 cm · Altura: 42 cm', 'Cajones de 48 × 40 × 15 cm', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 800 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] },
  { n: 'Modelo 12 Vip Plaza y Media', cat: '1-plaza-y-media', medida: '100 × 190 cm', img: 'assets/productos/1-plaza-y-media-12-VIP.jpg', price: 480000,
    clientPhotos: ['assets/producto-fotos/12-vip-plaza-y-media-1.jpg'],
    resumen: '12 cajones y 2 bauleras.',
    specs: ['12 cajones: 4 de cada lado y 4 al pie', '2 bauleras en la cabecera de 51 × 38 × 40 cm', 'Medida total: 193 × 103 cm · Altura: 42 cm', 'Cajones laterales de 48 × 40 × 15 cm', 'Cajones al pie de 45 × 40 × 15 cm (4)', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 800 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] },

  // 2 Plazas
  { n: '8 Vip', cat: '2-plazas', medida: '140 × 190 cm', img: 'assets/productos/1-8-VIP.jpg', price: 499000, priceOld: 530000, oferta: true,
    clientPhotos: ['assets/producto-fotos/8-vip-1.jpg','assets/producto-fotos/8-vip-2.jpg','assets/producto-fotos/8-vip-3.jpg','assets/producto-fotos/8-vip-4.jpg','assets/producto-fotos/8-vip-5.jpg','assets/producto-fotos/8-vip-6.jpg','assets/producto-fotos/8-vip-7.jpg','assets/producto-fotos/8-vip-8.jpg','assets/producto-fotos/8-vip-9.jpg'],
    resumen: '8 cajones, 2 zapateros y 3 bauleras.',
    specs: ['8 cajones: 4 de cada lado', '1 baulera central de 102 × 50 × 40 cm', '2 bauleras en la cabecera de 68 × 38 × 40 cm', '2 zapateros al pie de 65 cm de ancho cada uno', 'Medida total: 193 × 143 cm · Altura: 42 cm', 'Cajones de 48 × 40 × 15 cm', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 1000 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] },
  { n: 'Modelo 4 Vip', cat: '2-plazas', medida: '140 × 190 cm', img: 'assets/productos/1-4-VIP.jpg', price: 470000,
    clientPhotos: ['assets/producto-fotos/4-vip-1.jpg','assets/producto-fotos/4-vip-2.jpg','assets/producto-fotos/4-vip-3.jpg','assets/producto-fotos/4-vip-4.jpg','assets/producto-fotos/4-vip-5.jpg','assets/producto-fotos/4-vip-6.jpg','assets/producto-fotos/4-vip-7.jpg','assets/producto-fotos/4-vip-8.jpg'],
    resumen: '4 cajones, 2 zapateros y 3 bauleras.',
    specs: ['4 cajones laterales', '1 baulera central de 102 × 50 × 40 cm', '2 bauleras en la cabecera de 68 × 38 × 40 cm', '2 zapateros al pie de 65 cm de ancho cada uno', 'Medida total: 193 × 143 cm · Altura: 42 cm', 'Cajones de 48 × 40 × 30 cm', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 1000 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] },
  { n: 'Modelo 6 Vip', cat: '2-plazas', medida: '140 × 190 cm', img: 'assets/productos/1-6-VIP.jpg', price: 490000,
    clientPhotos: ['assets/producto-fotos/6-vip-1.jpg','assets/producto-fotos/6-vip-2.jpg','assets/producto-fotos/6-vip-3.jpg','assets/producto-fotos/6-vip-4.jpg','assets/producto-fotos/6-vip-5.jpg','assets/producto-fotos/6-vip-6.jpg','assets/producto-fotos/6-vip-7.jpg','assets/producto-fotos/6-vip-8.jpg','assets/producto-fotos/6-vip-9.jpg','assets/producto-fotos/6-vip-10.jpg'],
    resumen: '6 cajones y 3 bauleras.',
    specs: ['6 cajones: 4 laterales y 2 al pie', '1 baulera central de 102 × 50 × 40 cm', '2 bauleras en la cabecera de 68 × 38 × 40 cm', 'Medida total: 193 × 143 cm · Altura: 42 cm', 'Cajones laterales de 48 × 40 × 30 cm', 'Cajones al pie de 65 × 40 × 30 cm (2)', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 1000 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] },
  { n: 'Modelo con Estantes Vip', cat: '2-plazas', medida: '140 × 190 cm', img: 'assets/productos/Modelo-Cajones-VIP.jpg', price: 490000,
    resumen: '6 cajones, 6 estantes en los pies y 3 bauleras.',
    specs: ['6 cajones laterales', '1 baulera central de 102 × 50 × 40 cm', '2 bauleras en la cabecera de 68 × 38 × 40 cm', '6 estantes en los pies de 70 cm de ancho, 19 de alto y 45 de profundidad', 'Medida total: 193 × 143 cm · Altura: 42 cm', 'Cajones de 48 × 40 × 30 cm', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 1000 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] },
  { n: 'Modelo 10 Vip', cat: '2-plazas', medida: '140 × 190 cm', img: 'assets/productos/4.jpg', price: 550000,
    clientPhotos: ['assets/producto-fotos/10-vip-1.jpg','assets/producto-fotos/10-vip-2.jpg','assets/producto-fotos/10-vip-3.jpg','assets/producto-fotos/10-vip-4.jpg','assets/producto-fotos/10-vip-5.jpg','assets/producto-fotos/10-vip-6.jpg','assets/producto-fotos/10-vip-7.jpg'],
    resumen: '10 cajones y 3 bauleras.',
    specs: ['10 cajones: 4 de cada lado y 2 al pie', '1 baulera central de 102 × 50 × 40 cm', '2 bauleras en la cabecera de 68 × 38 × 40 cm', 'Medida total: 193 × 143 cm · Altura: 42 cm', 'Cajones laterales de 48 × 40 × 30 cm', 'Cajones al pie de 65 × 40 × 30 cm (2)', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 1000 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] },
  { n: 'Modelo 12 Vip', cat: '2-plazas', medida: '140 × 190 cm', img: 'assets/productos/1-12-VIP.jpg', price: 570000,
    clientPhotos: ['assets/producto-fotos/12-vip-1.jpg','assets/producto-fotos/12-vip-2.jpg','assets/producto-fotos/12-vip-3.jpg','assets/producto-fotos/12-vip-4.jpg','assets/producto-fotos/12-vip-5.jpg','assets/producto-fotos/12-vip-6.jpg'],
    resumen: '12 cajones y 3 bauleras.',
    specs: ['12 cajones: 4 de cada lado y 4 al pie', '1 baulera central de 102 × 50 × 40 cm', '2 bauleras en la cabecera de 68 × 38 × 40 cm', 'Medida total: 193 × 143 cm · Altura: 42 cm', 'Cajones laterales de 48 × 40 × 15 cm', 'Cajones al pie de 48 × 40 × 15 cm (4)', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 1000 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] },
  { n: 'Modelo 18 Vip', cat: '2-plazas', medida: '140 × 190 cm', img: 'assets/productos/18-VIP.jpg', price: 770000,
    clientPhotos: ['assets/producto-fotos/18-vip-1.jpg','assets/producto-fotos/18-vip-2.jpg','assets/producto-fotos/18-vip-3.jpg','assets/producto-fotos/18-vip-4.jpg'],
    resumen: '18 cajones y 3 bauleras.',
    specs: ['18 cajones: 6 de cada lado y 6 al pie', '1 baulera central grande', '2 bauleras en la cabecera', 'Medida total: 193 × 143 cm · Altura: 52 cm', 'Cajones laterales de 48 × 40 × 15 cm', 'Cajones al pie de 64 × 40 × 12 cm (6)', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 1000 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] },

  // Queen
  { n: 'Modelo 4 Vip Queen', cat: 'queen', medida: '160 × 200 cm', img: 'assets/productos/1-4-VIP.jpg', price: 500000,
    clientPhotos: ['assets/producto-fotos/4-vip-1.jpg','assets/producto-fotos/4-vip-2.jpg','assets/producto-fotos/4-vip-3.jpg','assets/producto-fotos/4-vip-4.jpg','assets/producto-fotos/4-vip-5.jpg','assets/producto-fotos/4-vip-6.jpg','assets/producto-fotos/4-vip-7.jpg','assets/producto-fotos/4-vip-8.jpg'],
    resumen: '4 cajones, 2 zapateros y 3 bauleras.',
    specs: ['4 cajones laterales', '1 baulera central de 102 × 70 × 40 cm', '2 bauleras en la cabecera de 78 × 44 × 40 cm', '2 zapateros al pie de 75 cm de ancho cada uno', 'Medida total: 203 × 163 cm · Altura: 42 cm', 'Cajones de 48 × 40 × 30 cm', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 1000 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] },
  { n: 'Modelo 6 Vip Queen', cat: 'queen', medida: '160 × 200 cm', img: 'assets/productos/1-6-VIP.jpg', price: 520000,
    clientPhotos: ['assets/producto-fotos/6-vip-1.jpg','assets/producto-fotos/6-vip-2.jpg','assets/producto-fotos/6-vip-3.jpg','assets/producto-fotos/6-vip-4.jpg','assets/producto-fotos/6-vip-5.jpg','assets/producto-fotos/6-vip-6.jpg','assets/producto-fotos/6-vip-7.jpg','assets/producto-fotos/6-vip-8.jpg','assets/producto-fotos/6-vip-9.jpg','assets/producto-fotos/6-vip-10.jpg'],
    resumen: '6 cajones y 3 bauleras.',
    specs: ['6 cajones: 4 laterales y 2 al pie', '1 baulera central de 102 × 70 × 40 cm', '2 bauleras en la cabecera de 78 × 44 × 40 cm', 'Medida total: 203 × 163 cm · Altura: 42 cm', 'Cajones laterales de 48 × 40 × 30 cm', 'Cajones al pie de 75 × 40 × 30 cm (2)', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 1000 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] },
  { n: 'Modelo 8 Vip Queen', cat: 'queen', medida: '160 × 200 cm', img: 'assets/productos/1-8-VIP.jpg', price: 530000, priceOld: 560000, oferta: true,
    clientPhotos: ['assets/producto-fotos/8-vip-1.jpg','assets/producto-fotos/8-vip-2.jpg','assets/producto-fotos/8-vip-3.jpg','assets/producto-fotos/8-vip-4.jpg','assets/producto-fotos/8-vip-5.jpg','assets/producto-fotos/8-vip-6.jpg','assets/producto-fotos/8-vip-7.jpg','assets/producto-fotos/8-vip-8.jpg','assets/producto-fotos/8-vip-9.jpg'],
    resumen: '8 cajones, 2 zapateros y 3 bauleras.',
    specs: ['8 cajones: 4 de cada lado', '1 baulera central de 102 × 70 × 40 cm', '2 bauleras en la cabecera de 78 × 44 × 40 cm', '2 zapateros al pie de 75 cm de ancho cada uno', 'Medida total: 203 × 163 cm · Altura: 42 cm', 'Cajones de 48 × 40 × 15 cm', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 1000 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] },
  { n: 'Modelo 10 Vip Queen', cat: 'queen', medida: '160 × 200 cm', img: 'assets/productos/4.jpg', price: 580000,
    clientPhotos: ['assets/producto-fotos/10-vip-1.jpg','assets/producto-fotos/10-vip-2.jpg','assets/producto-fotos/10-vip-3.jpg','assets/producto-fotos/10-vip-4.jpg','assets/producto-fotos/10-vip-5.jpg','assets/producto-fotos/10-vip-6.jpg','assets/producto-fotos/10-vip-7.jpg'],
    resumen: '10 cajones y 3 bauleras.',
    specs: ['10 cajones: 4 de cada lado y 2 al pie', '1 baulera central de 102 × 70 × 40 cm', '2 bauleras en la cabecera de 78 × 44 × 40 cm', 'Medida total: 203 × 163 cm · Altura: 42 cm', 'Cajones laterales de 48 × 40 × 30 cm', 'Cajones al pie de 75 × 40 × 30 cm (2)', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 1000 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] },
  { n: 'Modelo 12 Vip Queen', cat: 'queen', medida: '160 × 200 cm', img: 'assets/productos/1-12-VIP.jpg', price: 600000,
    clientPhotos: ['assets/producto-fotos/12-vip-1.jpg','assets/producto-fotos/12-vip-2.jpg','assets/producto-fotos/12-vip-3.jpg','assets/producto-fotos/12-vip-4.jpg','assets/producto-fotos/12-vip-5.jpg','assets/producto-fotos/12-vip-6.jpg'],
    resumen: '12 cajones y 3 bauleras.',
    specs: ['12 cajones: 4 de cada lado y 4 al pie', '1 baulera central de 102 × 70 × 40 cm', '2 bauleras en la cabecera de 78 × 44 × 40 cm', 'Medida total: 203 × 163 cm · Altura: 42 cm', 'Cajones laterales de 48 × 40 × 15 cm', 'Cajones al pie de 48 × 40 × 15 cm (4)', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 1000 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] },
  { n: 'Modelo Estantes Vip Queen', cat: 'queen', medida: '160 × 200 cm', img: 'assets/productos/Modelo-Cajones-VIP-1.jpg', price: 520000,
    resumen: '6 cajones, 6 estantes en los pies y 3 bauleras.',
    specs: ['6 cajones laterales', '1 baulera central de 102 × 70 × 40 cm', '2 bauleras en la cabecera de 78 × 44 × 40 cm', '6 estantes en los pies de 80 cm de ancho, 19 de alto y 45 de profundidad', 'Medida total: 203 × 163 cm · Altura: 42 cm', 'Cajones de 48 × 40 × 30 cm', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 1000 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] },
  { n: 'Modelo 18 Vip Queen', cat: 'queen', medida: '160 × 200 cm', img: 'assets/productos/18-VIP.jpg', price: 800000,
    clientPhotos: ['assets/producto-fotos/18-vip-1.jpg','assets/producto-fotos/18-vip-2.jpg','assets/producto-fotos/18-vip-3.jpg','assets/producto-fotos/18-vip-4.jpg'],
    resumen: '18 cajones y 3 bauleras.',
    specs: ['18 cajones: 6 de cada lado y 6 al pie', '1 baulera central grande', '2 bauleras en la cabecera', 'Medida total: 203 × 163 cm · Altura: 52 cm', 'Cajones laterales de 48 × 40 × 15 cm', 'Cajones al pie de 74 × 40 × 12 cm (6)', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 1000 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] },

  // King 180x200
  { n: '8 Vip King', cat: 'king', subcat: 'king-180', medida: 'King 180 × 200 cm', img: 'assets/productos/1-King-8.jpg', price: 680000,
    clientPhotos: ['assets/producto-fotos/king-8-vip-1.jpg','assets/producto-fotos/king-8-vip-2.jpg','assets/producto-fotos/king-8-vip-3.jpg','assets/producto-fotos/king-8-vip-4.jpg'],
    resumen: '8 cajones, 3 zapateros y 5 bauleras.',
    specs: ['8 cajones: 4 de cada lado', '2 bauleras centrales de 102 × 45 × 40 cm', '3 bauleras en la cabecera: 2 de 70 × 43 × 40 cm y 1 de 43 × 43 × 40 cm', '3 zapateros al pie: 2 de 65 y 1 de 45 cm de ancho (6 pares cada uno)', 'Medida total: 203 × 183 cm · Altura: 42 cm', 'Cajones de 48 × 40 × 15 cm', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 1000 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] },
  { n: '14 Vip King', cat: 'king', subcat: 'king-180', medida: 'King 180 × 200 cm', img: 'assets/productos/1-King-14.jpg', price: 730000,
    clientPhotos: ['assets/producto-fotos/king-14-vip-1.jpg','assets/producto-fotos/king-14-vip-2.jpg','assets/producto-fotos/king-14-vip-3.jpg','assets/producto-fotos/king-14-vip-4.jpg','assets/producto-fotos/king-14-vip-5.jpg'],
    resumen: '14 cajones y 5 bauleras.',
    specs: ['14 cajones: 4 de cada lado y 6 al pie', '2 bauleras centrales de 102 × 45 × 40 cm', '3 bauleras en la cabecera: 2 de 70 × 43 × 40 cm y 1 de 43 × 43 × 40 cm', 'Medida total: 203 × 183 cm · Altura: 42 cm', 'Cajones laterales de 48 × 40 × 15 cm', 'Cajones al pie de 65 × 40 × 15 cm (4)', 'Cajones al pie de 38 × 40 × 15 cm (2)', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 1000 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] },
  { n: '21 Vip King', cat: 'king', subcat: 'king-180', medida: 'King 180 × 200 cm', img: 'assets/productos/1-King-21.jpg', price: 880000,
    clientPhotos: ['assets/producto-fotos/king-21-vip-1.jpg'],
    resumen: '21 cajones y 5 bauleras.',
    specs: ['21 cajones: 6 de cada lado y 9 al pie', '2 bauleras centrales de 102 × 45 × 50 cm', '3 bauleras en la cabecera: 2 de 70 × 43 × 50 cm y 1 de 43 × 43 × 50 cm', 'Medida total: 203 × 183 cm · Altura: 52 cm', 'Cajones laterales de 48 × 40 × 12 cm', 'Cajones al pie de 65 × 40 × 12 cm (6)', 'Cajones al pie de 38 × 40 × 12 cm (3)', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 1000 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] },
  // King 200x200
  { n: '8 Vip King', cat: 'king', subcat: 'king-200', medida: 'King 200 × 200 cm', img: 'assets/productos/1-King-8.jpg', price: 700000,
    clientPhotos: ['assets/producto-fotos/king-8-vip-1.jpg','assets/producto-fotos/king-8-vip-2.jpg','assets/producto-fotos/king-8-vip-3.jpg','assets/producto-fotos/king-8-vip-4.jpg'],
    resumen: '8 cajones, 3 zapateros y 5 bauleras.',
    specs: ['8 cajones: 4 de cada lado', '2 bauleras centrales de 102 × 55 × 40 cm', '3 bauleras en la cabecera: 2 de 70 × 43 × 40 cm y 1 de 63 × 43 × 40 cm', '3 zapateros al pie: 2 de 65 y 1 de 55 cm de ancho (6 pares cada uno)', 'Medida total: 203 × 203 cm · Altura: 42 cm', 'Cajones de 48 × 40 × 15 cm', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 1000 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] },
  { n: '14 Vip King', cat: 'king', subcat: 'king-200', medida: 'King 200 × 200 cm', img: 'assets/productos/1-King-14.jpg', price: 750000,
    clientPhotos: ['assets/producto-fotos/king-14-vip-1.jpg','assets/producto-fotos/king-14-vip-2.jpg','assets/producto-fotos/king-14-vip-3.jpg','assets/producto-fotos/king-14-vip-4.jpg','assets/producto-fotos/king-14-vip-5.jpg'],
    resumen: '14 cajones y 5 bauleras.',
    specs: ['14 cajones: 4 de cada lado y 6 al pie', '2 bauleras centrales de 102 × 55 × 40 cm', '3 bauleras en la cabecera: 2 de 70 × 43 × 40 cm y 1 de 63 × 43 × 40 cm', 'Medida total: 203 × 203 cm · Altura: 42 cm', 'Cajones laterales de 48 × 40 × 15 cm', 'Cajones al pie de 65 × 40 × 15 cm (4)', 'Cajones al pie de 58 × 40 × 15 cm (2)', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 1000 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] },
  { n: '21 Vip King', cat: 'king', subcat: 'king-200', medida: 'King 200 × 200 cm', img: 'assets/productos/1-King-21.jpg', price: 900000,
    clientPhotos: ['assets/producto-fotos/king-21-vip-1.jpg'],
    resumen: '21 cajones y 5 bauleras.',
    specs: ['21 cajones: 6 de cada lado y 9 al pie', '2 bauleras centrales de 102 × 55 × 50 cm', '3 bauleras en la cabecera: 2 de 70 × 43 × 50 cm y 1 de 63 × 43 × 50 cm', 'Medida total: 203 × 203 cm · Altura: 52 cm', 'Cajones laterales de 48 × 40 × 12 cm', 'Cajones al pie de 65 × 40 × 12 cm (6)', 'Cajones al pie de 58 × 40 × 12 cm (3)', 'Melamina Egger de 15 mm, blanca por dentro y por fuera, con cantos ABS termofusionados', 'Soporta hasta 1000 kg', 'Correderas telescópicas reforzadas Eurohard, el cajón sale 40 cm'] }
];

const COLORS = [
  { n: 'Blanco', sw: '#FFFFFF', compare: 'assets/showroom/compare-blanca.jpg' },
  { n: 'Wengue', sw: '#3B2A1D', tex: 'assets/colores/texture-wengue.jpg', compare: 'assets/showroom/compare-wengue.jpg' },
  { n: 'Roble Kendall', sw: '#A9825A', tex: 'assets/colores/texture-roble-kendall.jpg', compare: 'assets/showroom/compare-roble-kendall.jpg' },
  { n: 'Nogal Pacífico', sw: '#7A5433', tex: 'assets/colores/texture-nogal-pacifico.jpg', compare: 'assets/showroom/compare-nogal-pacifico.jpg' },
  { n: 'Negro', sw: '#1B1512', compare: 'assets/showroom/compare-negro.jpg' },
  { n: 'Gris Perla', sw: '#B9B4AE', compare: 'assets/showroom/compare-gris-perla.jpg' },
  { n: 'Gris Sombra', sw: '#6E6862', compare: 'assets/showroom/compare-gris-sombra.jpg' },
  { n: 'Kentoky', sw: '#8C6B4A', tex: 'assets/colores/texture-kentoky.jpg', compare: 'assets/showroom/compare-kentoky.jpg' }
];
const CAMA_BLANCA = 'assets/showroom/compare-blanca.jpg';
